version: '3.5'

services:
  my_app:
    container_name: flask
    restart: on-failure
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app/database.db:/parser/database.db
    ports:
      - 50001:50001
    command: python3 app.py
